/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<timer.h>
#include<stdio.h>

int i = 0;
int main(void)
{
	RCC->AHB1ENR |= (1U<<0);

	GPIOA->MODER |= (1U<<10);

	usart2_txRx_init();
	tim2_1hz_init();

	while(1)
	{
		//wait for UIF bit
		while(!(TIM2->SR & SR_UIF));

		// clear the bit
		TIM2->SR &= ~(1U<<0);

		printf(" %d \r\n",i);
		i++;
	}


}
